#!/bin/bash

echo "*********DELETE_USER_SCRIPT*********"
echo  "active now: $(users)"
read -p "Specify the user to delete:  " user

# Stop all running process for the user
check_active=`pgrep -u $user`
if [ "$check_active != "$NULL ]; then
	pgrep -u $user | while read PID; do sudo kill -9 $PID;
done
# Delete user
sudo userdel -r $user
echo "the active user deleted"
fi
